### PR TITLE
remove duplicate call to monit_shell_out! on start_service

### PR DESCRIPTION
**Pull request by gretel**
possibly related to https://github.com/poise/poise-monit/issues/6

### CODE REVIEW

**Comment by coderanger** [comment]
That is intentional, the Monit in Ubuntu 12.04 and 14.04 seems to require either waiting 5+ minutes between monitor and start or calling start twice.

**Comment by gretel** [comment]
are you sure about that? it seems like a reasonable cause for the errors i get.
from my experience there is no need to wait 5 minutes for anything related to minig. if your monitoring interval is that long - maybe.. but i usually go for 60 seconds or less.

**Comment by coderanger** [comment]
Yes, there is a regression test for it in the TK stuffs. If you remove one of those and run `kitchen verify ubuntu` you'll see intermittent failures.

**Comment by gretel** [comment]
how about a slight delay between the calls?

**Comment by coderanger** [comment]
I tried delays before and after the start call, anything less than a 300 second delay before it didn't seem to help. If you can get the tests to pass I'm happy to change it to whatever though, this was definitely a "I have no idea what is happening but this makes the tests pass reliably" solution :-(

**Comment by gretel** [comment]
monit doc reads:

```
start name

    Start the named service and enable monitoring for it. The name is a service entry name from the monitrc file.
```

**Comment by coderanger** [comment]
Yes? Is your point that I don't need both the monitor and start as separate calls? If so, that is a side effect of Chef's service resource (which this has to match structurally) having start and enable as separate actions.

**Comment by gretel** [comment]
actually i think the test is problematic as well:

```
    context 'with status Not monitored' do
      let(:status) { 'Not monitored' }
      it do
        stub_cmd('start')
        stub_cmd('start')
        subject
      end
    end # /context with status Not monitored
```

**Comment by gretel** [comment]
@coderanger sorry, very much so, when starting a service it's state will be monitored. makes sense from systems management as well as a monit logic standpoint, i'd say.

**Comment by coderanger** [comment]
Yes, however the default use structure for the `service` resource is `action [:enable, :start]` and the best mapping for enable is monitor.

**Comment by coderanger** [comment]
That unit test matches the current behavior because it is a unit test, not an integration test. If you can get your code working with the Test Kitchen integration tests I can fix the unit tests to match.

**Comment by gretel** [comment]
well but chef won't be able to change how monit works. enabled is comparable to "in the config". there is no state that matches.

**Comment by coderanger** [comment]
Not really, a disabled service in most systems still exists, but isn't being checked/updated. This is like an unmonitored service in Monit.

**Comment by coderanger** [comment]
The weirdness is that start in Monit is enable+start in a lot of other systems so if the provider could collapse actions we could save some time, but that isn't how Chef is structured.

**Comment by gretel** [comment]
i think you misunderstand what the states mean in terms of monit. `unmonitor` is intended to be used when a service is _running_ so you can mess around with it and have monit _not_ to interfere. when you are finished manually you are going to enable `monitor` again - either to have monit resume checking or start the service (because human might have brought it down) so it's state in the end will always be _monitored_.

```
monitor name

    Enable monitoring of the named service. The name is a service entry name from the monitrc file. Monit will also enable monitoring of all services this service depends on.
```

not the third sentence - this will interfere.

**Comment by coderanger** [comment]
Yes, and that's fine, I agree that in a perfect model `[enable, start]` with Monit would collapse to a single start command, but that would break the abstraction. Using `action :disable` should leave the service in an unmonitored state, so for parity I need to have `action :enable` put it back.

**Comment by gretel** [comment]
again, `enable` does really not match the command of `monitor` nor the state of `monitored` in monit.

**Comment by coderanger** [comment]
It does when paired with `disable` is my point. For example, if you have a partial run list for an application deploy that does a service disable, runs a bunch of deploy commands, and then runs a service enable. That use case should work. Because of that I map enable to monitor.

**Comment by gretel** [comment]
i feel like this is really the issue in regards to the fact that there is no other plausible reason for the race condition i have. if `enable` does `start` a service two times monit behaves as expected on fast systems.

**Comment by coderanger** [comment]
But really this is all moot, given the existing integration tests if you can get them to pass then I'm cool with the change. But I know for a fact that this patch breaks them because that's how it worked originally :-)

**Comment by gretel** [comment]
well but i feel the test is just wrong. you just wouldn't accept my changes as you already did based upon the assumption that the test might actually reflect how monit works.

**Comment by gretel** [comment]
differently put, i have been using monit for a long time with and without automation. trigger `start` twice? use `monitor` to _not_ start a service? sorry, but i have never done that because it does not work.

**Comment by coderanger** [comment]
I think you are looking at the wrong test, I don't mean the unit tests, I mean this: https://github.com/poise/poise-monit/blob/master/lib/poise_monit/resources/monit_test.rb#L80-L109

Those are based on straight up normal use case for the resources. If those function correctly ([relevant specs](https://github.com/poise/poise-monit/blob/master/test/integration/default/serverspec/default_spec.rb#L40-L51)) then I would say things are working.

**Comment by coderanger** [comment]
The unit tests are tied to the implementation, but those can be changed if the implementation changes. The integration tests are designed to simulate vaguely real-world usage and verify that it really works.

**Comment by coderanger** [comment]
I would love a solution that doesn't involve a werido "run start twice" solution, but I was unable to find one.

**Comment by gretel** [comment]
well, in real-world things fail just now :) thanks for all the comments, going to report when i get back to work tomorrow.

**Comment by coderanger** [comment]
Roger, if you have a proposed change but can't get the integration suite working locally let me know and I can run them. Travis can't run them for you for security reasons unfortunately.

**Comment by gretel** [comment]
alternatively having a `:setup – Create and enable the service.` action on the service resource would also add some flexibility. add statement to configuration and leave service in whatever state it is.

**Comment by coderanger** [comment]
I can't add new actions easily, `monit_service` is an actual subclass of Chef's `sevice` code. Hence having to kind of hamfist the model a bit.

**Pull request closed without merging**
